### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by stephenbnicar** [kodosexe/F1Hub#1]
When I run the program, I get the following:

```
>python3 main.py 
Traceback (most recent call last):
  File "/Users/stephen/f1hub/main.py", line 42, in <module>
    event_menu = TerminalMenu(event_menu_items,
TypeError: __init__() takes 2 positional arguments but 6 positional arguments (and 2 keyword-only arguments) were given
```

Thanks for your work on this, by the way.

**Comment by kodosexe** [comment]
That is a weird error. It loads up the Terminal Menu module, but init seems to be different.

What OS are you on?

**Comment by ius** [comment]
`simple-term-menu` released a v1.0 with breaking API changes 4 hours prior to this bug report. Installing 0.11 instead works fine.

**Comment by kodosexe** [comment]
Thank you! I will make sure to note that in the Readme

**Comment by ius** [comment]
Just to add to that: when installing in a fresh virtualenv I also needed to install `requests`

**Comment by kodosexe** [comment]
I just updated the code to accomodate the new version, and it seems to be backwards compatible, so no big trouble should ensue.
Closing this now

**Comment by stephenbnicar** [comment]
It's working after the update.  Thanks!
