### ISSUE TITLE
Consider Adding a License

### ISSUE THREAD

**Issue by anthonylavado** [kodosexe/F1Hub#2]
Hey there!
It's great to see the work you've done so quickly with Python. To ensure that everyone in the community can benefit, have you considered adding a formal license to the project?
Most F1TV related projects seem to either use the MIT License, or even GPL v3.

GitHub has some helpful information you can review here: https://choosealicense.com

Thanks!

**Comment by kodosexe** [comment]
I just added the GPL v3 license. Thanks for the suggestion!
