### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by nkls23** [kodosexe/F1Hub#4]
Maybe I'm just dumb but I followed your install guide and got the F1Hub directory installed but when I try to execute python3 main.py I get this response: 

python3 main.py
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't open file '/Users/$/main.py': [Errno 2] No such file or directory

Let me know if you can help

**Comment by kodosexe** [comment]
It seems that you try to run the file from the home directory.
You're trying to run
Home/main.py

Assuming that main.py is in the f1Hub folder, you should be running
home/f1Hub/main.py

This assumes you have the f1Hub folder in home.
You can see the contents of the folder you're in with the 'ls' command. If you see an entry named 'f1Hub', you need to enter

```
cd f1Hub
python3 main.py
```

If you don't see f1Hub in the list after running ls, you are in the wrong folder. You will need to find the folder first (Try downloads?), enter it and then run the command again.

Let me know whether this helps!

**Comment by nkls23** [comment]
I think I got it to the right directory now. Unfortunately, I'm getting this response now: 

:f1Hub  python3 main.py
Traceback (most recent call last):
  File "/Users/$/f1hub/main.py", line 6, in <module>
    import getSeasonUrl
  File "/Users/$/f1hub/getSeasonUrl.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kodosexe** [comment]
Yup, that't the right directory.

It seems that 'requests' isn't included in the package by default. Run
```sh
pip install requests
```
And, just to make sure to cover all dependencies:
```sh
pip install pyperclip
```
Are you on Windows? I'll add to the readme that it's not installed by default.
Let me know whether this works

**Comment by nkls23** [comment]
I'm on MacOS Catalina. I installed pyperclip but with no luck. Same response. 

`pip install requests`

that gives me this:

`ERROR: Could not find a version that satisfies the requirement request
ERROR: No matching distribution found for request`

**Comment by kodosexe** [comment]
Odd.
Try the following, one should work:
```sh
pip -m install requests
pip3 -m install requests
```
If both fail, you may need to upgrade pip:
```sh
curl https://bootstrap.pypa.io/get-pip.py | python
```
and try the above.

If everything fails, you can try to download the mac file from the release tab, though i might have just discovered an issue with that, so you might have to wait until I fix that

**Comment by nkls23** [comment]
> ```shell
> pip -m install requests
> pip3 -m install requests
> ```

Both of those give me this response: 
```
:~ $ pip -m install requests

Usage:   
  pip <command> [options]

no such option: -m
```

Usage:   
  pip <command> [options]

no such option: -m
`

> 
> If both fail, you may need to upgrade pip:
> 
> ```shell
> curl https://bootstrap.pypa.io/get-pip.py | python
> ```
> 
> and try the above.
> 

On this it gives me: 
`:~ $ curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1882k  100 1882k    0     0   854k      0  0:00:02  0:00:02 --:--:--  854k
ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/2.7/get-pip.py instead.`


> If everything fails, you can try to download the mac file from the release tab, though i might have just discovered an issue with that, so you might have to wait until I fix that
> 
> _Edit:_ The issue with the relase file has been fixed.

I've got the f1Hub-pre-0.9-mac file downloaded. How do I execute it in python? Sorry if this is a stupid question. I'm really not that skilled in this. 

Thanks for your help!

**Comment by kodosexe** [comment]
You don't have to execute it in python, actually. Go to the folder containing the file and run
```sh
sudo chmod +x f1Hub-pre-0.9-mac
./f1Hub-pre-0.9-mac
```
It should work like that

Btw, the issue your computer has is that it's still running python2, which is no longer supported and reached it's end of life in December 2020.
Most stuff almost exclusively supports python version 3+ now, so it's recommended to update if you want to use Python in the future.

**Comment by nkls23** [comment]
Finally got it to work. Had to update Python to 3.7.3 and then redo the entire process. The manual install didn't seem to work 

> You don't have to execute it in python, actually. Go to the folder containing the file and run
> 
> ```shell
> sudo chmod +x f1Hub-pre-0.9-mac
> ./f1Hub-pre-0.9-mac
> ```
> 
> It should work like that

this kept coming up with:
`chmod: f1Hub-pre-0.9-mac: No such file or directory`

> 
> Btw, the issue your computer has is that it's still running python2, which is no longer supported and reached it's end of life in December 2020.
> Most stuff almost exclusively supports python version 3+ now, so it's recommended to update if you want to use Python in the future.

Thanks for your help! Looking forward to trying it out as an alternative to F1Viewer.

**Comment by kodosexe** [comment]
Yeah, Python 3 is the way to go now.
I see a lot of people having an issue with "No such file or directory" today :smile: 
Always make sure you're in the right directory.
Either way, I'm happy you got it working and I hope you like it!
