### ISSUE TITLE
Unable to find application named 'mpv'

### ISSUE THREAD

**Issue by nherring07** [kodosexe/F1Hub#9]
When trying to play video on MPV I get the following error:

> Darwin
> Unable to find application named 'mpv'

OS: MacOS
Version pre-0.10

**Comment by nherring07** [comment]
I see that I'm at fault here.

**Comment by kodosexe** [comment]
Haha, glad to hear you got it fixed. How did you solve it? Just to know how to help others in the future.

Kodos

**Comment by nherring07** [comment]
I just needed to install the mpv player, haha. I didn't read the instructions well enough, but I'm happy to report that it's all in working order now. Ready for the race!
